consoles= [
    
    {
        "Название": "Sega Mega Drive",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/a/a1/Sega-Mega-Drive-JP-Mk1-Console-Set.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Sega",
        "Процессор": "Motorola 68000",
        "Такт. частота процессора (МГц)": 7.6,
        "Оперативная памяти (МБ)": 0.064,
        "Продано (млн.)": 39,
        "Поколение": 4,
        "Год выпуска": 1988
    },
    {
        "Название": "Nintendo Entertainment System",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/b/b2/NES-Console-Set.png",
        "Тип": "Домашняя",
        "Разработчик": "Nintendo",
        "Процессор": "Ricoh 2A03",
        "Такт. частота процессора (МГц)": 1.79,
        "Оперативная памяти (МБ)": 0.002,
        "Продано (млн.)": 61,
        "Поколение": 3,
        "Год выпуска": 1983
    },
    {
        "Название": "Super Nintendo",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Nintendo-Super-Famicom-Set-FL.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Nintendo",
        "Процессор": "Ricoh 5A22",
        "Такт. частота процессора (МГц)": 3.58,
        "Оперативная памяти (МБ)": 0.128,
        "Продано (млн.)": 49,
        "Поколение": 4,
        "Год выпуска": 1990
    },
    {
        "Название": "PC Engine",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/d/d0/TurboGrafx16-Console-Set.jpg",
        "Тип": "Домашняя",
        "Разработчик": "NEC",
        "Процессор": "Hudson Soft HuC6280",
        "Такт. частота процессора (МГц)": 7.16,
        "Оперативная памяти (МБ)": 0.008,
        "Продано (млн.)": 10,
        "Поколение": 4,
        "Год выпуска": 1987
    },
    {
        "Название": "PlayStation",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/6/60/PlayStation-SCPH-1000-with-Controller.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Sony",
        "Процессор": "R3000",
        "Такт. частота процессора (МГц)": 33.8688,
        "Оперативная памяти (МБ)": 2.0,
        "Продано (млн.)": 102,
        "Поколение": 5,
        "Год выпуска": 1994
    },
    {
        "Название": "Nintendo 64",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/1/11/N64-Console-Set.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Nintendo",
        "Процессор": "64-bit NEC VR4300",
        "Такт. частота процессора (МГц)": 93.75,
        "Оперативная памяти (МБ)": 4.0,
        "Продано (млн.)": 32,
        "Поколение": 5,
        "Год выпуска": 1996
    },
    {
        "Название": "Game Boy Advance",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Nintendo-Game-Boy-Advance-Purple-FL.jpg",
        "Тип": "Портативная",
        "Разработчик": "Nintendo",
        "Процессор": "ARM7TDMI",
        "Такт. частота процессора (МГц)": 16.78,
        "Оперативная памяти (МБ)": 0.288,
        "Продано (млн.)": 81,
        "Поколение": 6,
        "Год выпуска": 2001
    },
    {
        "Название": "Sega 32X",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Sega-Genesis-Model2-32X.jpg",
        "Тип": "Аддон",
        "Разработчик": "Sega",
        "Процессор": "Hitachi SH-2",
        "Такт. частота процессора (МГц)": 23.0,
        "Оперативная памяти (МБ)": 0.256,
        "Продано (млн.)": 1,
        "Поколение": 5,
        "Год выпуска": 1994
    },
    {
        "Название": "Dreamcast",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/0/07/Dreamcast-Console-Set.png",
        "Тип": "Домашняя",
        "Разработчик": "Sega",
        "Процессор": "Hitachi SH-4",
        "Такт. частота процессора (МГц)": 200.0,
        "Оперативная памяти (МБ)": 16.0,
        "Продано (млн.)": 9,
        "Поколение": 6,
        "Год выпуска": 1998
    },
    {
        "Название": "Game Gear",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Sega-Game-Gear-WB.png",
        "Тип": "Портативная",
        "Разработчик": "Sega",
        "Процессор": "Zilog Z80",
        "Такт. частота процессора (МГц)": 3.5,
        "Оперативная памяти (МБ)": 0.008,
        "Продано (млн.)": 10,
        "Поколение": 4,
        "Год выпуска": 1990
    },
    {
        "Название": "PlayStation Portable",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/4/46/Psp-1000.jpg",
        "Тип": "Портативная",
        "Разработчик": "Sony",
        "Процессор": "MIPS R4000",
        "Такт. частота процессора (МГц)": 222.0,
        "Оперативная памяти (МБ)": 32.0,
        "Продано (млн.)": 80,
        "Поколение": 7,
        "Год выпуска": 2004
    },
    {
        "Название": "Xbox 360",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/6/67/Microsoft-Xbox-360-E-wController.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Microsoft",
        "Процессор": "PowerPC Tri-Core Xenon",
        "Такт. частота процессора (МГц)": 3200.0,
        "Оперативная памяти (МБ)": 512.0,
        "Продано (млн.)": 84,
        "Поколение": 7,
        "Год выпуска": 2005
    },
    {
        "Название": "PlayStation 5",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/7/77/Black_and_white_Playstation_5_base_edition_with_controller.png",
        "Тип": "Домашняя",
        "Разработчик": "Sony",
        "Процессор": "8-core AMD Zen 2",
        "Такт. частота процессора (МГц)": 3500.0,
        "Оперативная памяти (МБ)": 16000.0,
        "Продано (млн.)": 61,
        "Поколение": 9,
        "Год выпуска": 2020
    },
    {
        "Название": "Nintendo Switch",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/8/88/Nintendo-Switch-wJoyCons-BlRd-Standing-FL.jpg",
        "Тип": "Гибридная",
        "Разработчик": "Nintendo",
        "Процессор": "ARM 4 Cortex-A57",
        "Такт. частота процессора (МГц)": 1020.0,
        "Оперативная памяти (МБ)": 4000.0,
        "Продано (млн.)": 143,
        "Поколение": 9,
        "Год выпуска": 2017
    },
    {
        "Название": "PlayStation 2",
        "Изображение": "https://gamespirit.org/image/PlayStation%202/preload_J5wIN_350.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Sony",
        "Процессор": "MIPS R5900 Emotion Engine",
        "Такт. частота процессора (МГц)": 294.912,
        "Оперативная памяти (МБ)": 32.0,
        "Продано (млн.)": 155,
        "Поколение": 6,
        "Год выпуска": 2000
    },
    {
        "Название": "Sega CD",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Sega-CD-Model1-Set.jpg",
        "Тип": "Аддон",
        "Разработчик": "Sega",
        "Процессор": "Motorola 68000",
        "Такт. частота процессора (МГц)": 12.5,
        "Оперативная памяти (МБ)": 0.512,
        "Продано (млн.)": 2,
        "Поколение": 4,
        "Год выпуска": 1991
    },
    {
        "Название": "Atari 2600",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/0/02/Atari-2600-Wood-4Sw-Set.png",
        "Тип": "Домашняя",
        "Разработчик": "Atari",
        "Процессор": "MOS Technology 6507",
        "Такт. частота процессора (МГц)": 1.19,
        "Оперативная памяти (МБ)": 0.000128,
        "Продано (млн.)": 30,
        "Поколение": 2,
        "Год выпуска": 1977
    },
    {
        "Название": "Xbox One",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/0/05/Microsoft-Xbox-One-Console-Set-wKinect.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Microsoft",
        "Процессор": "8-core APU",
        "Такт. частота процессора (МГц)": 1750.0,
        "Оперативная памяти (МБ)": 8000.0,
        "Продано (млн.)": 58,
        "Поколение": 8,
        "Год выпуска": 2013
    },
    {
        "Название": "Sega Master System",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Sega-Master-System-Set.jpg/1024px-Sega-Master-System-Set.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Sega",
        "Процессор": "Zilog Z80",
        "Такт. частота процессора (МГц)": 4.0,
        "Оперативная памяти (МБ)": 0.008,
        "Продано (млн.)": 13,
        "Поколение": 3,
        "Год выпуска": 1985
    },    
    {
        "Название": "Xbox",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Xbox-Console-wDuke-L.jpg/2560px-Xbox-Console-wDuke-L.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Microsoft",
        "Процессор": "Intel Pentium III",
        "Такт. частота процессора (МГц)": 733.0,
        "Оперативная памяти (МБ)": 64.0,
        "Продано (млн.)": 24,
        "Поколение": 6,
        "Год выпуска": 2001
    },
    {
        "Название": "Neo Geo",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Neo-Geo-AES-Console-Set.png/2560px-Neo-Geo-AES-Console-Set.png",
        "Тип": "Домашняя",
        "Разработчик": "SNK",
        "Процессор": "Motorola 68000",
        "Такт. частота процессора (МГц)": 12.0,
        "Оперативная памяти (МБ)": 0.064,
        "Продано (млн.)": 1.18,
        "Поколение": 4,
        "Год выпуска": 1990
    },
    {
        "Название": "Nintendo 3DS",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Nintendo-3DS-AquaOpen.png/1280px-Nintendo-3DS-AquaOpen.png",
        "Тип": "Портативная",
        "Разработчик": "Nintendo",
        "Процессор": "ARM11 MPCore",
        "Такт. частота процессора (МГц)": 268.0,
        "Оперативная памяти (МБ)": 128.0,
        "Продано (млн.)": 76,
        "Поколение": 8,
        "Год выпуска": 2011
    },                   
    {
        "Название": "Sega Saturn",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Sega-Saturn-JP-Mk2-Console-Set.png/1024px-Sega-Saturn-JP-Mk2-Console-Set.png",
        "Тип": "Домашняя",
        "Разработчик": "Sega",
        "Процессор": "Hitachi SH-2",
        "Такт. частота процессора (МГц)": 28.6,
        "Оперативная памяти (МБ)": 2.0,
        "Продано (млн.)": 9.26,
        "Поколение": 5,
        "Год выпуска": 1994
    },
    {
        "Название": "PC-FX",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/PC-FX-Console-Set.jpg/1024px-PC-FX-Console-Set.jpg",
        "Тип": "Домашняя",
        "Разработчик": "NEC",
        "Процессор": "NEC V810",
        "Такт. частота процессора (МГц)": 21.475,
        "Оперативная памяти (МБ)": 2.0,
        "Продано (млн.)": 0.3,
        "Поколение": 5,
        "Год выпуска": 1994
    },
    {
        "Название": "SG-1000",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Sega-SG-1000-Console-Set.jpg/1920px-Sega-SG-1000-Console-Set.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Sega",
        "Процессор": "Zilog Z80",
        "Такт. частота процессора (МГц)": 3.58,
        "Оперативная памяти (МБ)": 0.001,
        "Продано (млн.)": 0.16,
        "Поколение": 3,
        "Год выпуска": 1983
    },
    {
        "Название": "Nintendo GameCube",
        "Изображение": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/GameCube-Set.jpg/1024px-GameCube-Set.jpg",
        "Тип": "Домашняя",
        "Разработчик": "Nintendo",
        "Процессор": "IBM Gekko",
        "Такт. частота процессора (МГц)": 486.0,
        "Оперативная памяти (МБ)": 24.0,
        "Продано (млн.)": 21.74,
        "Поколение": 6,
        "Год выпуска": 2001
    }     
    
    
]